### ISSUE TITLE
关于安装命令行工具

### ISSUE THREAD

**Issue by XuOneDollar** [egret-labs/egret3d#1]
执行npm install cnpm -g
出现error，提升error信息为：
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "–g": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:

**Comment by WanderWang** [comment]
看起来这是因为您的 npm 出了一些问题，请尝试重新安装 NodeJS
