### ISSUE TITLE
我是一个Unity开发者但是根本看不懂你们的3D项目是怎么开始构建的

### ISSUE THREAD

**Issue by NianHanDad** [egret-labs/egret3d#10]
一个官方示例都没有。新手教程全是文字？ 真的是差劲

**Comment by WanderWang** [comment]
您可以看  http://developer.egret.com/cn/docs/3d/unityplugin/ 这篇文章完成  Unity插件的安装，然后 通过这篇文章 http://developer.egret.com/cn/docs/3d/renderer/scene/ 里的方法就可以运行了。
