### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by zirancn** [egret-labs/egret3d#11]
1、通过loadGroup加载一个通过unity导出的场景，需要先加载贴图，再加载材质，然后加载模型，最后加载场景描述文件，顺序不正确会导致解析出错。建议资源加载完成解析数据的时候如果相应的依赖资源没有加载，则先不加载，待loadScene的时候再处理一次依赖资源，或者别的方法使用加载解析更为灵活
2、由于1，现在每次修改场景，都需要手动去调整default.res.json里在的加载顺序。另外现在3D场景的文件类型太多，修改起来好麻烦，ResDepot里面还没有支持新的资源类型，管理起来非常费劲。是否可以考虑延用2D的加载类型，把解析类型放在文件头里面，方便统一管理资源。
3、vs开发，没有console.log的日志输出，这个还挺影响开发的
4、粒子系统现在没有prewarm。

**Comment by zirancn** [comment]
5、新的方式启动游戏，没有执行runEgret，导致SystemTicker里面的callLaters无法执行，因为没有player直接return

**Comment by WanderWang** [comment]
我建议您将这些问题逐个提出，而不是在一个 Issue 里一起提出来，这样有利于我们逐个跟踪。现在统一回答一下：

关于第一个问题，目前是建议您调用 RES.loadResAsync("scene.json") ，这样所有的文件就都会加载了，不要使用 loadGroup

第二个问题由于第一个解决了所以也不存在了

第三个问题您说的是 Visual Studio 还是 VSCode ？

第四个问题我们后续会考虑添加一下

第五个问题是个 BUG，我们会修复

**Comment by zirancn** [comment]
感谢回复!
第三个问题是指的Visual Studio
