### ISSUE TITLE
[bug]1、删除GameObject出错；2、Light.enabled无效 

### ISSUE THREAD

**Issue by designerlyj** [egret-labs/egret3d#12]
1、调用GameObject.destroy后出错
复现步骤 
构建如下层级的GameObject对象
```
MainObj
- bg
- GeoLayer
- - geo
- - - Img
Camera
```
然后调用geo.destroy()即出错 

2、把灯光egret3d.Light.enabled设为false不会关闭灯光 

我把demo附件上传在这个贴子了http://bbs.egret.com/thread-49362-1-1.html

**Comment by WanderWang** [comment]
收到，我们先分析一下

**Comment by WanderWang** [comment]
问题已经得到了解决，9月初发布的1.1版本
