### ISSUE TITLE
不能运行导出的小游戏工程

### ISSUE THREAD

**Issue by wetiontop** [egret-labs/egret3d#15]
导出小游戏工程后按照官方的修改后，还是无法运行起来，微信开发工具提示egret_native找不到。
环境：MacOS 10.13.6

**Comment by WanderWang** [comment]
最近我们的工程结构有一些调整，是这些调整导致了这个问题，预计下周就会解决

**Comment by wetiontop** [comment]
谢谢，解决了能临时给我们使用吗？还是要等正式发布后才行？

**Comment by WanderWang** [comment]
这两天就会发布了

**Comment by wetiontop** [comment]
@WanderWang 你好，发布了吗？在哪可以看到发布的公告？

**Comment by WanderWang** [comment]
@wetiontop 您好，刚才发布了，实测没有问题了，文档中心在此：http://developer.egret.com/cn/docs/3d/
