### ISSUE TITLE
希望能尽快出一版完整的api，英文的也行。我可以帮忙翻译。

### ISSUE THREAD

**Issue by rzdong** [egret-labs/egret3d#25]
打扰了~

**Comment by WanderWang** [comment]
API 文档在九月底已经发布了，但是目前有部分API尚未发布完整，我们正在努力完善每一个API的文档（包括这个国庆假期内），您也可以通过 fork egret3d 库然后通过在代码中添加注释的方式协助我们完善 API 文档。感谢您对 egret3d 的支持
