### ISSUE TITLE
1.2的完整开发者教程

### ISSUE THREAD

**Issue by tempest2023** [egret-labs/egret3d#27]
听说一月迭代一次版本，等1.2完整教程一个月了，这月中旬能更新出来吗？
跪求

**Comment by WanderWang** [comment]
您好，我们在10月8日更新的1.2 版本中完善了新手入门相关文档，具体链接在此：http://developer.egret.com/cn/docs/3d/tutorials/getting-started/README.html

如果您有后续其他文档需求，可以在这里回复，我们优先提供，目前我们后续文档主要会把Unity导出的进一步细节，还有2D 3D结合作为重点
