### ISSUE TITLE
egret3d 变更parent 没有考虑旋转角度的问题

### ISSUE THREAD

**Issue by Errol1017** [egret-labs/egret3d#32]
场景中有三级组件：空 gameObject parent0 > 空 gameObject parent1 > cube ；
步骤1，parent1 绕 -y 方向旋转 90度，此时 parent1 相对 parent0 旋转角度为 （0，-90，0）
步骤2，将 cube 的 parent 设为 parent0 ，cube.setParent(parent0, true) ，此时 cube 相对 parent0 旋转角度为（0，0，0），cube 相对世界旋转角度为（0，-90，0），此处相对世界旋转角度似乎是无效的。

在  unity3d 中，步骤2 之后 cube 相对 parent0 旋转角度为 （0，-90，0） 这应该才是合理的结果，或者是预期的结果。

我想了多种办法，但都无法解决这个问题，我把 parent1 相对 parent0 的旋转角度 应用到 cube 上，但多次旋转时，会出现旋转顺序不匹配的问题：比如 先 -y 旋转 90度，再 x 旋转 90度，最终的结果是 先 x 旋转 90度，再 -y 旋转 90度，这也不是预期的结果。旋转顺序是随机的。

我看了 setParent(value, worldPositionStays) 源码，但是没看到影响旋转角度的代码在哪，望指点。

谢谢！

**Comment by qibu111** [comment]
我这是重新给他设置了一下：       
       var position = this.transform.position;
        var euler = this.transform.euler;
        this.transform.parent = ball.transform;
        this.transform.position = position;//重新设置下位置
        this.transform.euler = euler;//重新设置下旋转

**Comment by akdcl** [comment]
感谢，这个 bug 将在 1.3 版本修复

**Comment by Errol1017** [comment]
> 我这是重新给他设置了一下：
> var position = this.transform.position;
> var euler = this.transform.euler;
> this.transform.parent = ball.transform;
> this.transform.position = position;//重新设置下位置
> this.transform.euler = euler;//重新设置下旋转

感谢！解决了上面的问题，但是我似乎又发现了一个问题：
场景中有两级组件：空 GameObject parent > cube ; 两个组件都在世界坐标系原点；
1，绕y轴：parent 绕世界原点 绕世界坐标系 y 轴 旋转 -10度；parent.rotateAngleAround(egret3d.Vector3.ZERO, egret3d.Vector3.UP, -10) ；
此时：parent.localEulerAngles = （0，-10，0）；parent.eulerAngles = （0，-10，0）；
cube.localEulerAngles = （0，0，0）；cube.eulerAngles = （0，-10，0）；
这是绕世界坐标系y轴的情况，这种情况似乎是没问题的；
2，绕x轴：parent 绕世界原点 绕世界坐标系 x 轴 旋转 10度；
parent.rotateAngleAround(egret3d.Vector3.ZERO, egret3d.Vector3.RIGHT, 10) ；
此时：parent.localEulerAngles = （10，0，0）；parent.eulerAngles = （10，0，0）；
cube.localEulerAngles = （0，0，0）；cube.eulerAngles = （90，0，0）；
此时绕 世界坐标系x轴旋转的度数： 大概 >1.25度时，cube.eulerAngles.x 一直是 90 ；0 - 1.25度 ，cube.eulerAngles.x 快速增加，没看出这两个值是什么关系。。
这里应该有问题
3，单独绕z轴，也是没问题的，但是只要加入绕 x 轴旋转，就会有问题；
4，这里的源码涉及matrix看不懂了，希望能给我修正后的代码，我在这里卡住了。。
5，再次感谢！

**Comment by Errol1017** [comment]
新版本后以上问题都已解决。
