### ISSUE TITLE
未找到paper-cli

### ISSUE THREAD

**Issue by ylkx2008** [egret-labs/egret3d#47]
按照

- 下载 EgretLauncher
- 在 https://github.com/egret-labs/egret-core/tree/5.3.x 下载 egret 5.3.2 版本引擎
- 通过 EgretLauncher的“安装本地引擎”的方式安装 egret 5.3.2
- 在命令行执行 egret versions，如果安装引擎列表里包含 5.3.2 则代表安装成功
- 下载并安装 Egret3D 编辑器

这个步骤安装完成egret3d后运行paper，提示 `未找到paper-cli`

**Comment by a85884875** [comment]
> 按照
> 
> * 下载 EgretLauncher
> * 在 https://github.com/egret-labs/egret-core/tree/5.3.x 下载 egret 5.3.2 版本引擎
> * 通过 EgretLauncher的“安装本地引擎”的方式安装 egret 5.3.2
> * 在命令行执行 egret versions，如果安装引擎列表里包含 5.3.2 则代表安装成功
> * 下载并安装 Egret3D 编辑器
> 
> 这个步骤安装完成egret3d后运行paper，提示 `未找到paper-cli`

社区里面有回答，需要用npm install @egret/paper-cli -g一下，如果还报paper-cli未找到是因为node.js的版本需要是8.0以上，更新下node的版本就好了

**Comment by ylkx2008** [comment]
感谢，解决了，感谢感谢，真的非常谢谢

**Comment by yanyuling** [comment]
按照如上步骤操作，还是提示 ### **未找到paper-cli** 
node -v v10.10.0

**Comment by WanderWang** [comment]
最新的 Egret Pro 已经解决了这个问题，不需要再依赖于用户自己本地安装的 paper-cli了
