### ISSUE TITLE
游戏物体子父级嵌套超过8层就显示不了了。Egret Pro 0.9

### ISSUE THREAD

**Issue by renegadelyp** [egret-labs/egret3d#52]
新下载了Egret Pro 0.9，创建项目后，就在项目里测试子父级嵌套。当套到第8层时，再创建的子集cube就无法再场景和树状结构图中显示出来了。但空位还有，双击空位会回到根父级那个cube上。

**Comment by renegadelyp** [comment]
复现方法：
创建一个新项目，在已有的cube上右键，创建一个该cube的子cube
以上操作重复7次（建议把每次创建出的cube挪出来）
当操作第8次时，游戏对象列表中应当出现新“cube”的地方，点开会呈空白状态。双击该空白会居中显示带logo的cube。同时，多次点击最后一层cube旁的展开按钮，将使游戏对象列表顶部出现大量空行。

**Comment by WanderWang** [comment]
问题已找到并在内部版本中修复，下个小版本会解决该问题

**Comment by WanderWang** [comment]
0.9.1 已经解决此问题
